//index
export const FETCH_BANNER_DATA = 'FETCH_BANNER_DATA'

export const FETCH_SHOPPING_CHANNEL = 'FETCH_SHOPPING_CHANNEL'

export const FETCH_HOT_SALL_PRODUCT = 'FETCH_HOT_SALL_PRODUCT'

export const FETCH_POPULAR_RECOMMENDS = 'FETCH_POPULAR_RECOMMENDS'

export const FETCH_FAST_ARRIVALS = 'FETCH_FAST_ARRIVALS'

export const FETCH_CATEGORY_GOODS = 'FETCH_CATEGORY_GOODS'


//items
export const FETCH_ITEMS_DATA = 'FETCH_ITEMS_DATA'

//detail
export const FETCH_GOODS_DETAIL_INFO = 'FETCH_GOODS_DETAIL_INFO'

//recommend 
export const FETCH_RECOMMEND_GOODS = 'FETCH_RECOMMEND_GOODS'

//comments
export const FETCH_COMMENTS = 'FETCH_COMMENTS'

export const FETCH_COMMENT_TAGS = 'FETCH_COMMENT_TAGS'

//search
export const FETCH_SEARCH_KEYWORDS = 'FETCH_SEARCH_KEYWORDS'

//catelist
export const FETCH_CATE_LIST = 'FETCH_CATE_LIST'

//marketDesc
export const FETCH_MARKET_DESC = 'FETCH_MARKET_DESC'

//topic 
export const FETCH_TOPIC_DATA = 'FETCH_TOPIC_DATA'
//manufacturer
export const FETCH_MANU_FACTURER_DATA = 'FETCH_MANU_FACTURER_DATA'
