//index
export const FETCH_BANNER_DATA = 'FETCH_BANNER_DATA'

export const FETCH_SHOPPING_CHANNEL = 'FETCH_SHOPPING_CHANNEL'

export const FETCH_HOT_SALL_PRODUCT = 'FETCH_HOT_SALL_PRODUCT'

export const FETCH_POPULAR_RECOMMENDS = 'FETCH_POPULAR_RECOMMENDS'

export const FETCH_FAST_ARRIVALS = 'FETCH_FAST_ARRIVALS'

export const FETCH_CATEGORY_GOODS = 'FETCH_CATEGORY_GOODS'


//items
export const FETCH_ITEMS_DATA = 'FETCH_ITEMS_DATA'